export const PERMISSIONS = {
  MANAGE_UNIVERSITIES: "MANAGE_UNIVERSITIES",

  MANAGE_COLLEGES: "MANAGE_COLLEGES",

  MANAGE_DEPARTMENTS: "MANAGE_DEPARTMENTS",

  MANAGE_CLASSROOMS: "MANAGE_CLASSROOMS",

  MANAGE_STUDENTS: "MANAGE_STUDENTS",

  CREATE_FORM: "CREATE_FORM",

  EDIT_FORM: "EDIT_FORM",

  DELETE_FORM: "DELETE_FORM",

  VIEW_FORM: "VIEW_FORM",

  SUBMIT_FORM: "SUBMIT_FORM",

  APPROVE_FORM: "APPROVE_FORM",

  EXPORT_DATA: "EXPORT_DATA",

  VIEW_ANALYTICS: "VIEW_ANALYTICS",
} as const;